name: Minimal OFP Dumper Workflow

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2
         
       - name: Clean Up
         uses: rokibhasansagar/slimhub_actions@main
        
       - name: Clone Ofp Dumper
         run: |
              git clone https://github.com/noobyysauraj/ofp-dumper ofp-dumper
                        
       - name: Setup OFP Dumper environment
         working-directory: ofp-dumper
         run: |
              sudo bash setup.sh

       - name: Setup config envs And Begin Dump
         working-directory: ofp-dumper
         shell: bash
         run: |
              export BOT_CHAT_ID="@saurajdumps"
              export GIT_ORG="sauraj-dumps"
              export GITLAB_TOKEN=${{ secrets.GITLAB_TOKEN }}
              export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
              bash ofp.sh "$ROM_URL" "$ROM_TYPE"

##########
env:
  ROM_URL: https://rms01.realme.net/sw/RMX2189export_11_C.13_2022070513330163.zip
  ROM_TYPE: https://rms01.realme.net/sw/RMX2189export_11_C.13_2022070513330163.zip
